Repository iamrakesh28/FriendBlend, pull requests merged in 2020-11, with the labels that each got.

#2 Add Color Correction
  .gitignore
  Makefile
  bin/README.md
  images/carBright.jpg
  images/ghostBright.jpg
  images/ghostDark.jpg
  images/vaderBright.jpeg
  src/README.md
  src/colorCorrect/claheMethod.cpp
  src/colorCorrect/claheMethod.hpp
  src/colorCorrect/colorCorrect.hpp
  src/colorCorrect/colorCorrection.hpp
  src/colorCorrect/histogramEqualizeMethod.cpp
  src/colorCorrect/histogramEqualizeMethod.hpp
  src/process/process.cpp
  src/process/process.hpp
  src/test/colorCorrect/claheMethod.cpp
  src/test/colorCorrect/histogramEqualizeMethod.cpp
  src/test/process/claheTest.cpp
  src/test/process/constrastStretchTest.cpp
  src/test/process/histogramEqualizeTest.cpp
Labels: enhancement

#1 Initialize Repository
  .gitignore
  Makefile
  bin/README.md
  src/README.md
Labels: initialize

#3 Face body Detection by Rakesh
  Makefile
  images/ahmed.jpg
  images/devansh.jpg
  images/rakesh.jpg
  images/vaibhav.jpg
  src/faceBodyDetect/faceBodyDetect.hpp
  src/faceBodyDetect/faceBodyDetection.hpp
  src/faceBodyDetect/haarCascade.cpp
  src/faceBodyDetect/haarCascade.hpp
  src/test/faceBodyDetect/haarCascadeTest.cpp
  src/test/process/claheTest.cpp
  src/utility/utility.cpp
  src/utility/utility.hpp
Labels: enhancement

#4 Add pkg-config at the end of the line
  Makefile
Labels: bug

#5 Add Image Align
  Makefile
  images/md.jpg
  images/md_rotate.jpg
  src/align/align.cpp
  src/align/align.hpp
  src/test/align/alignTest.cpp
  src/test/faceBodyDetect/haarCascadeTest.cpp
Labels: enhancement
